runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# Static JS files.
- url: /static/js
  static_dir: static/js

# Static CSS files.
- url: /static/css
  static_dir: static/css

- url: /static/img
  static_dir: static/image

- url: /.*
  script: main.application
